version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rag_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgvector:
    image: pgvector/pgvector:pg15
    container_name: rag_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    ports:
      - "5433:5432"
    volumes:
      - vector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rag_app:
    build: .
    container_name: rag_system_app
    depends_on:
      postgres:
        condition: service_healthy
      pgvector:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rag_system
      - VECTOR_DATABASE_URL=postgresql://postgres:password@pgvector:5432/vector_db
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python -m uvicorn api:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  vector_data:
  redis_data: